# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

myVar <- function(x, v) {
    .Call(`_RaceID_myVar`, x, v)
}

mySize <- function(x, v) {
    .Call(`_RaceID_mySize`, x, v)
}

ProbFun <- function(x, v, w) {
    .Call(`_RaceID_ProbFun`, x, v, w)
}

applyProb <- function(x, v, w) {
    .Call(`_RaceID_applyProb`, x, v, w)
}

applyNoise <- function(x, z, co, pv, pvM) {
    .Call(`_RaceID_applyNoise`, x, z, co, pv, pvM)
}

applyNoiseReg <- function(x, z, co, pv, pvM) {
    .Call(`_RaceID_applyNoiseReg`, x, z, co, pv, pvM)
}

rcpp_hello_world <- function() {
    .Call(`_RaceID_rcpp_hello_world`)
}

